"""add encryption_method to telegram_backups

Revision ID: 28ea71890b13
Revises: 54a35d5aa9ec
Create Date: 2026-02-18 22:09:27.620332+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ea71890b13'
down_revision: Union[str, None] = '54a35d5aa9ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_backups', sa.Column('encryption_method', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_backups', 'encryption_method')
    # ### end Alembic commands ###
