"""add_is_encrypted_to_telegram_backups

Revision ID: 54a35d5aa9ec
Revises: 81a60e8ba195
Create Date: 2026-02-18 21:19:37.124099+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a35d5aa9ec'
down_revision: Union[str, None] = '81a60e8ba195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_backups', sa.Column('is_encrypted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_backups', 'is_encrypted')
    # ### end Alembic commands ###
