"""add_telegram_backup_tables

Revision ID: 81a60e8ba195
Revises: 92405d6c93a2
Create Date: 2026-02-18 20:12:05.253280+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81a60e8ba195'
down_revision: Union[str, None] = '92405d6c93a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_backups',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_file_id', sa.String(), nullable=False),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.Column('backup_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('entity_counts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('version_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_backups_user_id'), 'telegram_backups', ['user_id'], unique=False)
    op.add_column('telegram_settings', sa.Column('backup_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('telegram_settings', sa.Column('backup_schedule', sa.String(length=16), server_default=sa.text("'daily'"), nullable=True))
    op.add_column('telegram_settings', sa.Column('backup_retention', sa.Integer(), server_default=sa.text('5'), nullable=False))
    op.add_column('telegram_settings', sa.Column('last_backup_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('telegram_settings', sa.Column('next_backup_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_settings', 'next_backup_at')
    op.drop_column('telegram_settings', 'last_backup_at')
    op.drop_column('telegram_settings', 'backup_retention')
    op.drop_column('telegram_settings', 'backup_schedule')
    op.drop_column('telegram_settings', 'backup_enabled')
    op.drop_index(op.f('ix_telegram_backups_user_id'), table_name='telegram_backups')
    op.drop_table('telegram_backups')
    # ### end Alembic commands ###
