"""add_todo_recurrence_columns

Revision ID: 246e02aed12a
Revises: d9e1e881f3ea
Create Date: 2026-02-14 18:39:42.257417+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246e02aed12a'
down_revision: Union[str, None] = 'd9e1e881f3ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add recurrence columns to todos table
    op.add_column('todos', sa.Column('recurrence_type', sa.String(length=20), nullable=True))
    op.add_column('todos', sa.Column('recurrence_interval', sa.Integer(), server_default=sa.text('1'), nullable=True))
    op.add_column('todos', sa.Column('recurrence_days', sa.String(length=20), nullable=True))
    op.add_column('todos', sa.Column('recurrence_end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('todos', sa.Column('recurrence_parent_id', sa.Uuid(), nullable=True))

    # Add foreign key constraint for recurrence_parent_id
    op.create_foreign_key(
        'fk_todos_recurrence_parent_id_todos',
        'todos', 'todos',
        ['recurrence_parent_id'], ['id'],
        ondelete='SET NULL'
    )

    # Add index on recurrence_parent_id
    op.create_index('idx_todos_recurrence_parent', 'todos', ['recurrence_parent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop index and foreign key (if they exist)
    op.execute('DROP INDEX IF EXISTS idx_todos_recurrence_parent')
    op.execute('ALTER TABLE todos DROP CONSTRAINT IF EXISTS fk_todos_recurrence_parent_id_todos')

    # Drop columns (if they exist)
    op.execute('ALTER TABLE todos DROP COLUMN IF EXISTS recurrence_parent_id')
    op.execute('ALTER TABLE todos DROP COLUMN IF EXISTS recurrence_end_date')
    op.execute('ALTER TABLE todos DROP COLUMN IF EXISTS recurrence_days')
    op.execute('ALTER TABLE todos DROP COLUMN IF EXISTS recurrence_interval')
    op.execute('ALTER TABLE todos DROP COLUMN IF EXISTS recurrence_type')

    # ### end Alembic commands ###
