"""add_users_passkey_credentials_webauthn_challenges

Revision ID: 92405d6c93a2
Revises: 246e02aed12a
Create Date: 2026-02-18 15:21:50.689231+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92405d6c93a2'
down_revision: Union[str, None] = '246e02aed12a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webauthn_challenges',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('challenge', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webauthn_challenges_expires_at'), 'webauthn_challenges', ['expires_at'], unique=False)
    op.create_table('passkey_credentials',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('transports', sa.Text(), nullable=True),
    sa.Column('backed_up', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('device_type', sa.String(length=20), server_default='single_device', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id')
    )
    op.create_index(op.f('ix_passkey_credentials_user_id'), 'passkey_credentials', ['user_id'], unique=False)
    op.drop_index(op.f('idx_notes_content_search'), table_name='notes', postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_notes_user_updated'), table_name='notes')
    op.drop_index(op.f('uq_tags_user_id_name'), table_name='tags')
    op.create_unique_constraint('uq_tags_user_id_name', 'tags', ['user_id', 'name'])
    op.drop_index(op.f('idx_todos_recurrence_parent'), table_name='todos')
    op.drop_index(op.f('idx_todos_reminder'), table_name='todos', postgresql_where='(reminder_at IS NOT NULL)')
    op.drop_index(op.f('idx_todos_user_parent_sort'), table_name='todos')
    op.create_index(op.f('ix_todos_recurrence_parent_id'), 'todos', ['recurrence_parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_recurrence_parent_id'), table_name='todos')
    op.create_index(op.f('idx_todos_user_parent_sort'), 'todos', ['user_id', 'parent_id', 'sort_order'], unique=False)
    op.create_index(op.f('idx_todos_reminder'), 'todos', ['reminder_at', 'reminder_sent'], unique=False, postgresql_where='(reminder_at IS NOT NULL)')
    op.create_index(op.f('idx_todos_recurrence_parent'), 'todos', ['recurrence_parent_id'], unique=False)
    op.drop_constraint('uq_tags_user_id_name', 'tags', type_='unique')
    op.create_index(op.f('uq_tags_user_id_name'), 'tags', ['user_id', 'name'], unique=True)
    op.create_index(op.f('idx_notes_user_updated'), 'notes', ['user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index(op.f('idx_notes_content_search'), 'notes', ['content'], unique=False, postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_passkey_credentials_user_id'), table_name='passkey_credentials')
    op.drop_table('passkey_credentials')
    op.drop_index(op.f('ix_webauthn_challenges_expires_at'), table_name='webauthn_challenges')
    op.drop_table('webauthn_challenges')
    op.drop_table('users')
    # ### end Alembic commands ###
