"""add_backup_password_to_telegram_settings

Revision ID: 7239f9a284c6
Revises: 28ea71890b13
Create Date: 2026-02-18 23:49:40.761568+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7239f9a284c6'
down_revision: Union[str, None] = '28ea71890b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_settings', sa.Column('backup_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_settings', 'backup_password')
    # ### end Alembic commands ###
