"""add_performance_indexes

Revision ID: e37af5048224
Revises: ebd3c2cb650a
Create Date: 2026-02-14 18:37:55.933951+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37af5048224'
down_revision: Union[str, None] = 'ebd3c2cb650a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Enable pg_trgm extension for trigram similarity search
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')

    # Notes table indexes
    op.create_index(
        'idx_notes_user_updated',
        'notes',
        ['user_id', sa.text('updated_at DESC')],
        unique=False
    )
    op.create_index(
        'idx_notes_content_search',
        'notes',
        ['content'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={'content': 'gin_trgm_ops'}
    )

    # Todos table indexes
    op.create_index(
        'idx_todos_user_parent_sort',
        'todos',
        ['user_id', 'parent_id', 'sort_order'],
        unique=False
    )
    op.create_index(
        'idx_todos_reminder',
        'todos',
        ['reminder_at', 'reminder_sent'],
        unique=False,
        postgresql_where='reminder_at IS NOT NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_todos_reminder', table_name='todos')
    op.drop_index('idx_todos_user_parent_sort', table_name='todos')
    op.drop_index('idx_notes_content_search', table_name='notes')
    op.drop_index('idx_notes_user_updated', table_name='notes')
    # ### end Alembic commands ###
