"""add tags and junction tables

Revision ID: d9e1e881f3ea
Revises: e37af5048224
Create Date: 2026-02-14 18:38:53.187446+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e1e881f3ea'
down_revision: Union[str, None] = 'e37af5048224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), server_default='#6b7280', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tags_user_id_name')
    )
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_table('note_tags',
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'tag_id')
    )
    op.create_index(op.f('ix_note_tags_tag_id'), 'note_tags', ['tag_id'], unique=False)
    op.create_table('todo_tags',
    sa.Column('todo_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['todo_id'], ['todos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('todo_id', 'tag_id')
    )
    op.create_index(op.f('ix_todo_tags_tag_id'), 'todo_tags', ['tag_id'], unique=False)
    op.drop_index(op.f('idx_notes_content_search'), table_name='notes', postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_notes_user_updated'), table_name='notes')
    op.add_column('todos', sa.Column('recurrence_type', sa.String(length=20), nullable=True))
    op.add_column('todos', sa.Column('recurrence_interval', sa.Integer(), server_default=sa.text('1'), nullable=True))
    op.add_column('todos', sa.Column('recurrence_days', sa.String(length=20), nullable=True))
    op.add_column('todos', sa.Column('recurrence_end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('todos', sa.Column('recurrence_parent_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('idx_todos_reminder'), table_name='todos', postgresql_where='(reminder_at IS NOT NULL)')
    op.drop_index(op.f('idx_todos_user_parent_sort'), table_name='todos')
    op.create_index(op.f('ix_todos_recurrence_parent_id'), 'todos', ['recurrence_parent_id'], unique=False)
    op.create_foreign_key(None, 'todos', 'todos', ['recurrence_parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('todos_recurrence_parent_id_fkey', 'todos', type_='foreignkey')
    op.drop_index(op.f('ix_todos_recurrence_parent_id'), table_name='todos')
    op.create_index(op.f('idx_todos_user_parent_sort'), 'todos', ['user_id', 'parent_id', 'sort_order'], unique=False)
    op.create_index(op.f('idx_todos_reminder'), 'todos', ['reminder_at', 'reminder_sent'], unique=False, postgresql_where='(reminder_at IS NOT NULL)')
    op.drop_column('todos', 'recurrence_parent_id')
    op.drop_column('todos', 'recurrence_end_date')
    op.drop_column('todos', 'recurrence_days')
    op.drop_column('todos', 'recurrence_interval')
    op.drop_column('todos', 'recurrence_type')
    op.create_index(op.f('idx_notes_user_updated'), 'notes', ['user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index(op.f('idx_notes_content_search'), 'notes', ['content'], unique=False, postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_todo_tags_tag_id'), table_name='todo_tags')
    op.drop_table('todo_tags')
    op.drop_index(op.f('ix_note_tags_tag_id'), table_name='note_tags')
    op.drop_table('note_tags')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
